version: '2'

networks:
  app-network:
    external: true
    driver: bridge

services:
  redis: 
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
  
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    ports:
      - 3002:3002
      - 27017:27017
    networks:
      - app-network
    

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MARIADB_DATABASE: db
      MYSQL_USER: root
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3001:3001"
      - "3310:3310"
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  
  app1eue:
    build: .
    container_name: app1eue
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5010 --debug
    environment:
      REGION: 'EUE'
    volumes:
      - .:/app
    ports:
      - "5010:5010"
    networks:
      - app-network
    depends_on:
      - redis
      - mariadb
      - mongodb

  app2eue:
    build: .
    container_name: app2eue
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5011 --debug
    environment:
      REGION: 'EUE'
    volumes:
      - .:/app
    ports:
      - "5011:5011"
    networks:
      - app-network
    depends_on:
      - redis
      - mariadb
      - mongodb

volumes:
  mongo-data:
  mongo-configdb:
  mariadb-data: