version: '2'

networks:
  app-network:
    external: true
    driver: bridge

services:
  redis-fra: 
    image: bitnami/redis:latest
    container_name: redis-fra
    volumes:
      - ./redis-fra:/data
    ports:
      - '6380:6380'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
  
  mongodb-fra:
    image: mongo:4.0.8
    container_name: mongodb-fra
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongo-data-fra:/data/db
      - mongo-configdb-fra:/data/configdb
    ports:
      - 27019:27019
    networks:
      - app-network
    

  mariadb-fra:
    image: mariadb
    container_name: mariadb-fra
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MARIADB_DATABASE: db
      MYSQL_USER: root
    volumes:
      - mariadb-data-fra:/var/lib/mysql
    ports:
      - "3003:3003"
    restart: always
    networks:
      - app-network

  nginx-fra:
    build: ./load_balancer/france
    container_name: nginx-fra
    ports:
      - "81:81"
    networks:
      - app-network
    depends_on:
      - fra-app-1
      - fra-app-2
  
  fra-app-1:
    build: .
    container_name: fra-app-1
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5011 --debug
    environment:
      REGION: 'FRA'
    volumes:
      - .:/app
    ports:
      - "5011:5011"
    networks:
      - app-network
    depends_on:
      - redis-fra
      - mariadb-fra
      - mongodb-fra

  fra-app-2:
    build: .
    container_name: fra-app-2
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5111 --debug
    environment:
      REGION: 'FRA'
    volumes:
      - .:/app
    ports:
      - "5111:5111"
    networks:
      - app-network
    depends_on:
      - redis-fra
      - mariadb-fra
      - mongodb-fra


volumes:
  redis-fra:
  mongo-data-fra:
  mongo-configdb-fra:
  mariadb-data-fra: