version: '2'

networks:
  app-network:
    driver: bridge

services:
  redis: 
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
  
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    hostname: localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    ports:
      - 3002:27017
    networks:
      - app-network
    

  mariadb:
    image: docker.io/library/mariadb:10.3
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MARIADB_DATABASE: db
    ports:
      - "3001:3306"
    restart: always

#    nginx:
#      image: nginx:latest
#      volumes:
#        - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      depends_on:
#        -app
#      ports:
#        -"80:80"
  # flask:
  #   build: .
  #   container_name: latter-router
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - redis
  #     - mariadb
  #     - mongodb

volumes:
  mongo-data:
  mongo-configdb:
  maria-data: