version: '2'

networks:
  app-network:
    external: true
    driver: bridge

services:
  redis-rom: 
    image: bitnami/redis:latest
    container_name: redis-rom
    volumes:
      - ./redis-rom:/data
    ports:
      - '6382:6382'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
  
  mongodb-rom:
    image: mongo:4.0.8
    container_name: mongodb-rom
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongo-data-rom:/data/db
      - mongo-configdb-rom:/data/configdb
    ports:
      - 27021:27021
    networks:
      - app-network
    

  mariadb-rom:
    image: mariadb
    container_name: mariadb-rom
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MARIADB_DATABASE: db
      MYSQL_USER: root
    volumes:
      - mariadb-data-rom:/var/lib/mysql
    ports:
      - "3005:3005"
    restart: always
    networks:
      - app-network

  nginx-rom:
    build: ./load_balancer/romania
    container_name: nginx-rom
    ports:
      - "83:83"
    networks:
      - app-network
    depends_on:
      - rom-app-1
      - rom-app-2  

  rom-app-1:
    build: .
    container_name: rom-app-1
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5013 --debug
    environment:
      REGION: 'ROM'
    volumes:
      - .:/app
    ports:
      - "5013:5013"
    networks:
      - app-network
    depends_on:
      - redis-rom
      - mariadb-rom
      - mongodb-rom

  rom-app-2:
    build: .
    container_name: rom-app-2
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5013 --debug
    environment:
      REGION: 'ROM'
    volumes:
      - .:/app
    ports:
      - "5113:5113"
    networks:
      - app-network
    depends_on:
      - redis-rom
      - mariadb-rom
      - mongodb-rom


volumes:
  redis-rom:
  mongo-data-rom:
  mongo-configdb-rom:
  mariadb-data-rom: