version: '2'

networks:
  app-network:
    external: true
    driver: bridge

services:
  redis-ind: 
    image: bitnami/redis:latest
    container_name: redis-ind
    volumes:
      - ./redis-ind:/data
    ports:
      - '6383:6383'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
  
  mongodb-ind:
    image: mongo:4.0.8
    container_name: mongodb-ind
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongo-data-ind:/data/db
      - mongo-configdb-ind:/data/configdb
    ports:
      - 27022:27022
    networks:
      - app-network
    

  mariadb-ind:
    image: mariadb
    container_name: mariadb-ind
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MARIADB_DATABASE: db
      MYSQL_USER: root
    volumes:
      - mariadb-data-ind:/var/lib/mysql
    ports:
      - "3007:3007"
    restart: always
    networks:
      - app-network

  nginx-ind:
    build: ./load_balancer/india
    container_name: nginx-ind
    ports:
      - "82:82"
    networks:
      - app-network
    depends_on:
      - ind-app-1
      - ind-app-2
  
  ind-app-1:
    build: .
    container_name: ind-app-1
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5012 --debug
    environment:
      REGION: 'IND'
    volumes:
      - .:/app
    ports:
      - "5012:5012"
    networks:
      - app-network
    depends_on:
      - redis-ind
      - mariadb-ind
      - mongodb-ind

  ind-app-2:
    build: .
    container_name: ind-app-2
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5112 --debug
    environment:
      REGION: 'IND'
    volumes:
      - .:/app
    ports:
      - "5112:5112"
    networks:
      - app-network
    depends_on:
      - redis-ind
      - mariadb-ind
      - mongodb-ind

volumes:
  redis-ind:
  mongo-data-ind:
  mongo-configdb-ind:
  mariadb-data-ind: