version: '2'

networks:
  app-network:
    external: true
    driver: bridge

services:
  redis-ire: 
    image: bitnami/redis:latest
    container_name: redis-ire
    volumes:
      - ./redis-ire:/data
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
  
  mongodb-ire:
    image: mongo:4.0.8
    container_name: mongodb-ire
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongo-data-ire:/data/db
      - mongo-configdb-ire:/data/configdb
    ports:
      - 27018:27018
    networks:
      - app-network
    

  mariadb-ire:
    image: mariadb
    container_name: mariadb-ire
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MARIADB_DATABASE: db
      MYSQL_USER: root
    volumes:
      - mariadb-data-ire:/var/lib/mysql
    ports:
      - "3001:3001"
    restart: always
    networks:
      - app-network

  nginx-ire:
    build: ./load_balancer/ireland
    container_name: nginx-ire
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - ire-app-1
      - ire-app-2
  
  ire-app-1:
    build: .
    container_name: ire-app-1
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5010 --debug
    environment:
      REGION: 'IRE'
    volumes:
      - .:/app
    ports:
      - "5010:5010"
    networks:
      - app-network
    depends_on:
      - redis-ire
      - mariadb-ire
      - mongodb-ire
  
  ire-app-2:
    build: .
    container_name: ire-app-2
    command: python -m flask --app latterouter run -h 0.0.0.0 --port=5110 --debug
    environment:
      REGION: 'IRE'
    volumes:
      - .:/app
    ports:
      - "5110:5110"
    networks:
      - app-network
    depends_on:
      - redis-ire
      - mariadb-ire
      - mongodb-ire

volumes:
  redis-ire:
  mongo-data-ire:
  mongo-configdb-ire:
  mariadb-data-ire: